#Freezing Lake


In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make('FrozenLake-v0', is_slippery=False)   #ambiente


In [3]:
action_space_size = env.action_space.n                           # Linha da tabela
state_space_size = env.observation_space.n                      # Coluna da tabela

q_table = np.zeros((state_space_size, action_space_size))       # Q-Table


In [4]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [6]:
rewards_all_episodes = []
# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()    #reseta o estado toda vez que começa um episódio

    done = False           #Para saber quando acabou o episodio
    rewards_current_episode = 0           #resetar as recompensas


    for step in range(max_steps_per_episode): 
      
        exploration_rate_threshold = random.uniform(0, 1)       #Numero r
        if exploration_rate_threshold > exploration_rate:       #Saber se vamos explorar ou exploitar o ambiente
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()     

        new_state, reward, done, info = env.step(action)   #Depois de chamar action temos esses dados

        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state      #atualiza o novo estado
        rewards_current_episode += reward   #atualizamos a recompensa

        if done == True:    #acabou o episódio, gg ou reporta time
          break             #se acabou volta pro episodio

    #Exploration rate decay

    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)   #colocamos a nossa recompensa numa lista das recompensas

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000



********Average reward per thousand episodes********

1000 :  0.2580000000000002
2000 :  0.7230000000000005
3000 :  0.9160000000000007
4000 :  0.9560000000000007
5000 :  0.9750000000000008
6000 :  0.9810000000000008
7000 :  0.9880000000000008
8000 :  0.9900000000000008
9000 :  0.9900000000000008
10000 :  0.9910000000000008


In [7]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.94148015 0.93206535 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099004 0.96059601]
 [0.96059601 0.         0.91317277 0.76019489]
 [0.91118863 0.77929148 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.37209025 0.         0.92614816 0.41157711]
 [0.6163861  0.81949698 0.98009998 0.        ]
 [0.9702987  0.99       0.         0.97029892]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.6717397  0.98999978 0.7093782 ]
 [0.98009717 0.98999999 1.         0.98009997]
 [0.         0.         0.         0.        ]]


In [8]:
for episode in range(3):
  
    state = env.reset()   #Resetar estado
    done = False          #acabou o episodio
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")  #Mostra o episodio
    
    time.sleep(1)   

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)    #Limpa o outup do notebook, wait=true espera limpar o outup quando tiver outro output
        env.render()               # Vai mostrar onde o nosso agente está de fato
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])             # A ação vai ser a que tem o maior q-valor da nossa q-tabela
        new_state, reward, done, info = env.step(action) # Tomamos essa ação

        if done:                         #se a ação acabou o episódio então ...
          clear_output(wait=True)        #
          env.render()                   #rendeziramos o ambiente para ver onde o agente parou desde o último passo 
          if reward == 1:                #ganhou
              print("****You reached the goal!****")
              time.sleep(3)
          else:                          #perdeu
              print("****You fell through a hole!****")
              time.sleep(3)
          clear_output(wait=True)
          break                         #novo episodio

        state = new_state             #muda estado

env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
